apiVersion: v1
kind: Secret
metadata:
  name: notetaker-secrets
  namespace: note-taker
type: Opaque
stringData:
  GEMINI_API_KEY: "replace-me"
  GEMINI_API_KEY_EVAL: "replace-me"
  IBM_STT_APIKEY: ""
  IBM_STT_URL: ""
  RTZR_CLIENT_ID: ""
  RTZR_CLIENT_SECRET: ""

