apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: notetaker-stt
spec:
  to:
    kind: Service
    name: notetaker-stt
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: notetaker-rag
spec:
  to:
    kind: Service
    name: notetaker-rag
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: notetaker-eval
spec:
  to:
    kind: Service
    name: notetaker-eval
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

